### ISSUE TITLE
Problem installing the plugin.

### ISSUE THREAD

**Issue by gustavoschmidt2** [PrathamGitHub/NITK_RS-GIS_17#15]
Hello, I'm having trouble installing the plugin, the following error is appearing:
![error](https://user-images.githubusercontent.com/96667013/149861571-d7d293c8-9ed2-42d0-915c-7008586a97b8.PNG)

**Comment by LEOXINGU** [comment]
Hi,

Please, change the gdal import to:

**from osgeo import gdal**

**Comment by LEOXINGU** [comment]
The code here are ok. You just need to upload into QGIS repository.
The last update was in 2020.

**Comment by PrathamGitHub** [comment]
Hi .. This issue is resolved in upcoming version .. thanks :)
