### ISSUE TITLE
/PrathamGitHub/NITK_RS-GIS_17/

### ISSUE THREAD

**Issue by miho-kiev** [PrathamGitHub/NITK_RS-GIS_17#2]
"error reading repository; server response is 200 OK but does not contain metadata. "

I have all the files of version 0.3; the tracker link works. Here is the metadata txt file.
This file contains metadata for your plugin. Since 
# version 2.0 of QGIS this is the proper way to supply 
# information about a plugin. The old method of 
# embedding metadata in __init__.py will 
# is no longer supported since version 2.0.

# This file should be included when you package your plugin.# Mandatory items:

[general]
name=RS&GIS
qgisMinimumVersion=2.0
description=Operates on raw satellite data (Landsat 1-8 & LISS) to produce standard outputs and user defined custom band outputs
version=0.3
author=Prathamesh Barane, G S Dwarakish
email=prathamesh.barane@gmail.com

about=Tool performs well defined algorithms on raw satellite data to produce popularly used outputs like > Land Surface Temperature (LST) > At. Satellite Brightness Temperature > Normalized Difference Vegetation Index (NDVI) > Normalized Difference Water Index (NDWI) > True Color Composite (TCC) > Flase Color Composite (FCC) > At Satellite Reflectance of available bands > At Satellite Radiance of available bands > Other user defined custom band outputs

tracker=https://github.com/PrathamGitHub/NITK_RS-GIS_17/issues
repository=https://github.com/PrathamGitHub/NITK_RS-GIS_17.git
# End of mandatory metadata

# Recommended items:

# Uncomment the following line and add your changelog:
changelog= correction for the reflectance calculation, memory management, bug fixed

# Tags are comma separated with spaces allowed
tags= LISS, Landsat, LST, Land Surface Temperature, brightness temperature, reflectance, radiance, NDVI, NDWI, index, vegetation, water index, TCC, FCC, color composite, cloud remove

homepage= https://github.com/PrathamGitHub/NITK_RS-GIS_17/blob/master/Information.pdf
category=Plugins
icon=icon.png
# experimental flag
experimental=False

# deprecated flag (applies to the whole plugin, not just a single version)
deprecated=False

What else should I look for?
Hope you can help!
Michael H.

**Comment by PrathamGitHub** [comment]
Dear Michael,

I am sorry but I did not get the exact problem that you are facing. Can you please elaborate what are you looking for?

**Comment by miho-kiev** [comment]
Hi,
the problem is that I have copied the plugin into the directory .../.qgis2/python/plugins but in QGIS it can not be loaded; "error reading repository; server response is 200 OK but does not contain metadata. "
I have all the files of version 0.3; the tracker link works.
Thanks for answering!
Michael H.

**Comment by PrathamGitHub** [comment]
Dear Miho,

Please make sure that the directory name is *'NITK_RS-GIS_17'* not
*'NITK_RS-GIS_17-master'*

Regards,
Prathamesh
