### ISSUE TITLE
AttributeError: 'str' object has no attribute '__getslice__'

### ISSUE THREAD

**Issue by amsantac** [PrathamGitHub/NITK_RS-GIS_17#3]
Hi. This is a very promising plugin. Thanks for your contribution,

I am trying to run the plugin with a custom band expression (as a test), as follows:

(NIR - Red)/(NIR + Red)

However I get an error: AttributeError: 'str' object has no attribute '__getslice__'

Any suggestions to solve it are welcome. Please see full-length output below,

Thanks!

Ali

>>>----------------------------------------------------------------------<<<
 ==============  Process Started ===============
>>>----------------------------------------------------------------------<<<

Collected all the user inputs
C:/amsantac/other/temp/data\NITK_RSGIS_20180517_113127
Folder "NITK_RSGIS_20180517_113127" created in (C:/amsantac/other/temp/data) directory

Extracting the file/s in the corresponding folder/s ...

>>>~~~
Extracting LE70070572000076EDC00.tar.gz file in ../NITK_RSGIS_20180517_113127/Extracted/LE70070572000076EDC00 folder.....

Time taken for extraction: 0 min. 5 sec.

>>> Please make sure:
        1. Selected input file/s contain/s metadata file/s

            Read metadata file/s and extracted the details
>>>----------------------------------------------------------------------<<<
Created "Outputs" folder to store all the outputs in the directory (NITK_RSGIS_20180517_113127)

Folders created in ../NITK_RSGIS_20180517_113127/Outputs directory:
    LE70070572000076EDC00.tar
>>>----------------------------------------------------------------------<<<

>>>~~~~~

Processing on the data of LE70070572000076EDC00.tar

>>> For custom output ndvi:

:-( Error:

 Traceback (most recent call last):
  File "C:/Users/Alí/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NITK_RS-GIS_17\RSGIS_M.py", line 2182, in run
    a = custom[out].__getslice__(0, i - 1 + n)
AttributeError: 'str' object has no attribute '__getslice__'

Process stopped in between ! You are good to go again.

**Comment by fernandaapt** [comment]
Hi, i'm having the same problem.
Did you find out the reason why?

**Comment by PrathamGitHub** [comment]
Hi .. Sorry for delayed response.. This issue is now resolved in upcoming version
