### ISSUE TITLE
Problems with the plug-in

### ISSUE THREAD

**Issue by rcabas** [PrathamGitHub/NITK_RS-GIS_17#4]
Hi,
I have some problem with this plug-in when I try to start it.
I attach the windows with the problem.
Can you tell me what I need to do?
Thanks!
![captura de pantalla 2018-05-28 a las 16 52 16](https://user-images.githubusercontent.com/39711017/40627848-b7a4b1ea-6297-11e8-91bb-eb0f1f45bbbd.png)

**Comment by PrathamGitHub** [comment]
Hi .. Sorry for delayed response .. This issue is now resolved in upcoming version
